# -*- coding: utf-8 -*-
"""encoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9ExHBqSG0hTgN9Mr5Nhle1hbhXPkXuI
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

data=pd.read_csv('/content/global_freelancers_raw.csv')

cat_cols = data.select_dtypes(include='object').columns
data_onehot = pd.get_dummies(data, columns=cat_cols, drop_first=True)

data_label = data.copy()
le = LabelEncoder()

for col in cat_cols:
    data_label[col] = le.fit_transform(data_label[col])

data_ordinal = data.copy()
ord_enc = OrdinalEncoder()
data_ordinal[cat_cols] = ord_enc.fit_transform(data_ordinal[cat_cols])

data_freq = data.copy()

for col in cat_cols:
    freq_map = data_freq[col].value_counts()
    data_freq[col] = data_freq[col].map(freq_map)







