# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VoinNBitfiEP2085ng29jCeUALh4_A5k
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

data=pd.read_csv('/content/global_freelancers_raw.csv')

data.isnull().sum()

data.head()

data.columns

data=data.drop_duplicates()
data

data.isnull().sum()

data.dtypes

data['hourly_rate (USD)']=pd.to_numeric(data['hourly_rate (USD)'],errors='coerce')
data

data['client_satisfaction']=pd.to_numeric(data['client_satisfaction'],errors='coerce')
data

num_cols=['age','years_of_experience','hourly_rate (USD)','rating','client_satisfaction']
for col in num_cols:
  data[col] = data[col].fillna(data[col].median())

data.isnull().sum()

data['is_active']=data['is_active'].fillna(data['is_active'].mode()[0])

data.isnull().sum()

data.dtypes

data['age']=data['age'].astype(int)
data['years_of_experience']=data['years_of_experience'].astype(int)

outlier_info = {}

for col in num_cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = data[(data[col] < lower_bound) | (data[col] > upper_bound)]
    outlier_info[col] = outliers.shape[0]

    print(f"{col}: {outliers.shape[0]} outliers")

num_cols = ['age', 'years_of_experience', 'hourly_rate (USD)', 'rating', 'client_satisfaction']

for col in num_cols:

    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    data[col] = data[col].clip(lower_bound, upper_bound)

    print(f"Treatment complete for {col}. Values capped at {lower_bound:.2f} and {upper_bound:.2f}.")

for col in num_cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    remaining = data[(data[col] < (Q1 - 1.5 * IQR)) | (data[col] > (Q3 + 1.5 * IQR))].shape[0]
    print(f"Remaining outliers in {col}: {remaining}")

data=data.drop_duplicates()

data.drop(columns=['freelancer_ID','name'], inplace=True, errors='ignore')



