# -*- coding: utf-8 -*-
"""Superviseddata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CD9w3OcrkZS5fsL_4Zak1Spy7-sFN0pf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

data=pd.read_csv('/content/student_exam_scores.csv')

data.isnull().sum()

data.info()

data.head()

data=data.drop_duplicates()

data=data.drop("student_id", axis=1)

X=data.drop("exam_score", axis=1)
y=data["exam_score"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model=LinearRegression()
model.fit(X_train, y_train)
y_train_pred=model.predict(X_train)
y_test_pred=model.predict(X_test)
def evaluate_model(y_true, y_pred, dataset_name="Dataset"):
    mae=mean_absolute_error(y_true, y_pred)
    mse=mean_squared_error(y_true, y_pred)
    rmse=np.sqrt(mse)
    r2=r2_score(y_true, y_pred)
    print(f"\n{dataset_name} Matrics:")
    print(f"MAE: {mae:.2f}")
    print(f"MSE: {mse:.2f}")
    print(f"RMSE: {rmse:.2f}")
    print(f"R² Score: {r2:.2f}")
evaluate_model(y_train, y_train_pred, "Training Set")
evaluate_model(y_test, y_test_pred, "Test Set")
X_vis=data[['hours_studied']]
y_vis=data['exam_score']
vis_model=LinearRegression()
vis_model.fit(X_vis, y_vis)
y_vis_pred=vis_model.predict(X_vis)
sorted_idx=X_vis['hours_studied'].argsort()
X_sorted=X_vis.iloc[sorted_idx]
y_sorted=y_vis_pred[sorted_idx]
plt.figure(figsize=(8, 5))
plt.scatter(X_vis, y_vis)
plt.plot(X_sorted, y_sorted)
plt.xlabel("Hours Studied")
plt.ylabel("Exam Score")
plt.title("Linear Regression:Hours Studied v/s Exam Score")
plt.show()

X = data[['hours_studied', 'sleep_hours', 'attendance_percent', 'previous_scores']]
y = data["exam_score"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
y_pred = lr_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse:.2f}")
print(f"R-squared Score: {r2:.2f}")
print(f"Coefficients: {list(zip(X.columns, lr_model.coef_))}")
print(f"Intercept: {lr_model.intercept_:.2f}")
plt.scatter(y_test, y_pred, color='yellow')
plt.xlabel('Actual Exam score')
plt.ylabel('Predicted Exam score')
plt.title('Multi-variable Linear Regression: Actual vs Predicted Scores')
plt.plot([y.min(), y.max()], [y.min(), y.max()], color='red', linewidth=2)
plt.show()

X=data.drop("exam_score", axis=1)
y=data["exam_score"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model=DecisionTreeRegressor(random_state=42)
model.fit(X_train, y_train)
y_train_pred=model.predict(X_train)
y_test_pred=model.predict(X_test)
def evaluate_model(y_true, y_pred, dataset_name="Dataset"):
    mae=mean_absolute_error(y_true, y_pred)
    mse=mean_squared_error(y_true, y_pred)
    rmse=np.sqrt(mse)
    r2=r2_score(y_true, y_pred)
    print(f"\n{dataset_name} Matrics:")
    print(f"MAE: {mae:.2f}")
    print(f"MSE: {mse:.2f}")
    print(f"RMSE: {rmse:.2f}")
    print(f"R² Score: {r2:.2f}")
evaluate_model(y_train, y_train_pred, "Training Set")
evaluate_model(y_test, y_test_pred, "Test Set")
param_grid={
    'max_depth': [None] + list(np.arange(1, 21)),
    'min_samples_split': np.arange(2, 21),
    'min_samples_leaf': np.arange(1, 21)
}
grid = GridSearchCV(
      DecisionTreeRegressor(random_state=42),
      param_grid,
      cv=5,
      scoring='r2',
      n_jobs=-1
 )
grid.fit(X_train, y_train)
best_tree=grid.best_estimator_
y_test_pred_best=best_tree.predict(X_test)
print("\nBest hyperparameters found:", grid.best_params_)
evaluate_model(y_train, best_tree.predict(X_train), "Training Set (Best Tree)")
evaluate_model(y_test, y_test_pred_best, "Test Set (Best Tree)")

data.columns

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
X = data.drop("exam_score", axis=1)
y = data["exam_score"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)
y_train_pred = rf_model.predict(X_train)
y_test_pred = rf_model.predict(X_test)
def evaluate_model(y_true, y_pred, dataset_name="Dataset"):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    print(f"\n{dataset_name} Metrics:")
    print(f"MAE: {mae:.2f}")
    print(f"MSE: {mse:.2f}")
    print(f"RMSE: {rmse:.2f}")
    print(f"R² Score: {r2:.2f}")
evaluate_model(y_train, y_train_pred, "Training Set")
evaluate_model(y_test, y_test_pred, "Test Set")
param_grid = {
     'n_estimators': [50, 100],
    'max_depth': [None, 10],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt']
}
grid = GridSearchCV(
    RandomForestRegressor(random_state=42),
    param_grid,
    cv=5,
    scoring='r2',
    n_jobs=-1
)
grid.fit(X_train, y_train)
best_rf = grid.best_estimator_
y_train_pred_best = best_rf.predict(X_train)
y_test_pred_best = best_rf.predict(X_test)
print("\nBest hyperparameters:", grid.best_params_)
evaluate_model(y_train, y_train_pred_best, "Training Set")
evaluate_model(y_test, y_test_pred_best, "Test Set")













